SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR="141"
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_COLOR=069
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL="➜"
SPACESHIP_CHAR_SYMBOL_ROOT="↯"

# GIT OPTIONS
SPACESHIP_GIT_ASYNC=false
SPACESHIP_GIT_BRANCH_COLOR=041
SPACESHIP_GIT_STATUS_COLOR=178
